/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ocp20_thread;

/**
 *
 * @author MB-study
 */
public class MyStockClient extends javax.swing.JFrame {

   private MyStockController controller;
   
    public MyStockClient() {
        initComponents();
        //第一次進來要做的事
        controller = new MyStockController(symbolLabel.getText(),priceLabel,changLabel);
       new Thread(controller).start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        symbolLabel = new javax.swing.JTextField();
        priceLabel = new javax.swing.JLabel();
        changLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        symbolLabel.setFont(new java.awt.Font("新細明體", 0, 18)); // NOI18N
        symbolLabel.setText("USDTWD=x");
        symbolLabel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                symbolLabelActionPerformed(evt);
            }
        });
        symbolLabel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                symbolLabelKeyPressed(evt);
            }
        });

        priceLabel.setFont(new java.awt.Font("新細明體", 0, 48)); // NOI18N
        priceLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        priceLabel.setText("00.00");
        priceLabel.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                priceLabelAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        changLabel.setFont(new java.awt.Font("新細明體", 0, 24)); // NOI18N
        changLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        changLabel.setText("00.00");
        changLabel.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                changLabelAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(symbolLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(priceLabel)
                    .addComponent(changLabel))
                .addContainerGap(113, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(symbolLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(priceLabel)
                .addGap(28, 28, 28)
                .addComponent(changLabel)
                .addContainerGap(94, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void symbolLabelKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_symbolLabelKeyPressed
       if(evt.getKeyCode() == 10){ //按下 Enter 鍵
           if(controller != null){
               controller.play = false;
               controller = new MyStockController(symbolLabel.getText(),priceLabel,changLabel);
               new Thread(controller).start();
           }
       }
    }//GEN-LAST:event_symbolLabelKeyPressed

    private void symbolLabelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_symbolLabelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_symbolLabelActionPerformed

    private void changLabelAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_changLabelAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_changLabelAncestorAdded

    private void priceLabelAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_priceLabelAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_priceLabelAncestorAdded

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MyStockClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MyStockClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MyStockClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MyStockClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MyStockClient().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel changLabel;
    private javax.swing.JLabel priceLabel;
    private javax.swing.JTextField symbolLabel;
    // End of variables declaration//GEN-END:variables
}
